### ISSUE TITLE
如何禁用了两个函数。服务启动不起来

### ISSUE THREAD

**Issue by cryhac** [slince/spike#13]
如果禁用函数proc_open和stream_socket_server两个函数将会报错（默认lnmp是禁用的）

PHP Warning:  stream_set_blocking() expects parameter 1 to be resource, null given in /root/.config/composer/vendor/react/socket/src/TcpServer.php on line 166
[2018-08-17 17:43:18] INFO: The server is running ...
[2018-08-17 17:43:48] INFO: Client Total: 0; Chunk Server Total: 0
[2018-08-17 17:44:18] INFO: Memory usage: 2523784

但是服务并没有起来。建议添加这两个函数的禁用情况进行异常处理。

解决办法：修复php.ini将这两个函数启用。

**Comment by slince** [comment]
这些函数一般在web应用上是用不到的，所以php都是默认给禁掉的，spike是一个cli应用，不是web应用，
所以这些函数是必要的

**Comment by slince** [comment]
感谢提issue，对后面的人可能会有帮助

**Comment by cryhac** [comment]
我的意思是说，如果禁用了，抛个异常会让后人少走弯路。而且很多人就是个人开发。默认的很多使用lnmp安装的。

**Comment by slince** [comment]
ok
