### ISSUE TITLE
路由重启后，一直没有重连……

### ISSUE THREAD

**Issue by wu1990** [slince/spike#4]
路由重启后，一直没有重连（Spike），

我看服务器配置，隧道还在线，实际上肯定连不上了，

然后我将服务器（spiked）也重启，还是没有重连。

**Comment by wu1990** [comment]
日志 ： error, message: The tunnel has been registered

**Comment by wu1990** [comment]
@slince 对的，本来隧道是同的，然后重启了路由器（猫），然后一直没连上，我就重启了 spiked 

上面的是客户端日志

**Comment by slince** [comment]
客户端的链接超时是30秒  并且进行第二次重连的时候没有提示；所以你可能误以为客户端卡死了‘我在新版本改了提示，缩短了超时时间为5秒，多次重连加了计数器提示； 待会packagist更新的时候 你再重新试试

**Comment by slince** [comment]
>  error, message: The tunnel has been registered
看这个情况应该是，猫重启以后，服务端没有接收到客户端掉线的消息所以仍然为客户端保留了隧道的配置；但客户端已经掉线，所以当它再次向服务端重连时服务端直接拒绝，所以客户端就自行关闭了

**Comment by slince** [comment]
@wu1990 我在新版修改了重连提示，缩短了重连的超时，优化了一些代码；待会packagist更新的时候你更新下看看
