### ISSUE TITLE
客户端和服务端互相有心跳包检测机制吗？？？

### ISSUE THREAD

**Issue by hijk1234** [slince/spike#6]
客户端和服务端：
heartbeat_interval = 15
heartbeat_timeout = 40
比如这种的？可以自定义设置的，tcp

**Comment by slince** [comment]
有，50s，客户端会发送给服务端更新自己的状态；服务端运行了一个定时器，长期没有更新的客户端会被断开

**Comment by slince** [comment]
[https://github.com/slince/spike/blob/master/src/Server/Timer/ReviewClient.php](https://github.com/slince/spike/blob/master/src/Server/Timer/ReviewClient.php) 服务端检查

[https://github.com/slince/spike/blob/master/src/Client/Timer/Heartbeat.php](https://github.com/slince/spike/blob/master/src/Client/Timer/Heartbeat.php) 客户端心跳

**Comment by hijk1234** [comment]
服务端不用对客户端发心跳包吗?

**Comment by slince** [comment]
> 服务端不用对客户端发心跳包吗

不需要，服务端做好客户端心跳请求的处理就好；spike里对心跳包的处理只是更新了client的活跃时间，以防止被扫描定时器关闭

处理代码：
[https://github.com/slince/spike/blob/master/src/Server/Handler/PingHandler.php](https://github.com/slince/spike/blob/master/src/Server/Handler/PingHandler.php)


> 另外有windows X32 X64版本的realease吗

spike是使用php实现的并不能像frp那样打包生成exe文件；由于php本身是跨平台的，所以spike在三个平台都是可以执行的，预先装好php就好
