### ISSUE TITLE
阿里云的云虚拟主机只有不可执行命令控制台和FTP服务该怎样进行安装

### ISSUE THREAD

**Issue by acmery** [slince/spike#7]
阿里云的云虚拟主机控制台
https://help.aliyun.com/knowledge_detail/36152.html?spm=a2c4g.11186631.2.1.yjIAC4
阿里云的FTP服务
https://help.aliyun.com/knowledge_detail/36241.html?spm=a2c4g.11186631.2.1.aIE3rg

1. 求教 —— spike使用的环境要求仅是PHP运行环境吗？
2. 求教 —— 仅有一个PHP运行环境想要运行spike是需要写一个安装的PHP程序吗？

**Comment by slince** [comment]
> spike使用的环境要求仅是PHP运行环境吗？
是的

> 求教 —— 仅有一个PHP运行环境想要运行spike是需要写一个安装的PHP程序吗？
没看懂；安装了composer, 按照命令即可安装

**Comment by acmery** [comment]
你好，可能是我第二个问题未描述清楚

阿里云的云虚拟主机  —— 其实仅仅是一个PHP主机空间 不能够执行命令行

> 请问能够直接把PHP代码放到虚拟主机空间进行运行吗？

非常谢谢你耐心的回答

**Comment by slince** [comment]
> 请问能够直接把PHP代码放到虚拟主机空间进行运行吗？

不可以spike是一个终端程序，不是web程序，所以没办法执行命令的话是没法用的

**Comment by acmery** [comment]
明白了 非常谢谢你耐心的回答

> 若是知道那个web程序能够实现这个功能，望给予提示，非常感谢！

**Comment by slince** [comment]
不会有web程序做这个的，web程序是网站，这个属于服务
