### ISSUE TITLE
服务端运行出错。。。

### ISSUE THREAD

**Issue by xx19941215** [slince/spike#9]
![image](https://user-images.githubusercontent.com/10104328/40277720-b0710924-5c56-11e8-843d-f01b4ec046a6.png)

**Comment by wujunze** [comment]
+1 
![image](https://user-images.githubusercontent.com/12997869/40957921-ce9aa73c-68c9-11e8-8d7a-ed2e301d916e.png)

**Comment by slince** [comment]
冲突 #10

**Comment by slince** [comment]
重构版本已经发布，你可以试下；
